wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    code_path: code/code/lstm.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.10
    start_time: 1660400734.516326
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 16
      - 23
      - 24
      4: 3.9.10
      5: 0.13.1
      8:
      - 4
      - 5
