#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --array=4-8%4
#SBATCH --job-name=data_creation
#SBATCH --time=0:5:0
#SBATCH --mem=100M
#SBATCH --output=output/data_combi_%A_%a.out

module purge
module load 2022
module load Miniconda3/4.12.0

HPARAMS_FILE=$HOME/MScThesis/code/jobs/hyper_data_combi.txt

cd $HOME/MScThesis/code
source activate thesis

cd $HOME/MScThesis/code
srun python create_combi_data.py $(head -$SLURM_ARRAY_TASK_ID $HPARAMS_FILE | tail -1)