#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --array=1-19%19
#SBATCH --job-name=gru_presentation
#SBATCH --time=2:30:0
#SBATCH --output=output/gru_presentation_array_%A_%a.out

module purge
module load 2022
module load Miniconda3/4.12.0

HPARAMS_FILE=$HOME/MScThesis/code/jobs/hyper_presentation_test.txt

cd $HOME/MScThesis/code
source activate thesis

cd $HOME/MScThesis/code
srun python gru.py $(head -$SLURM_ARRAY_TASK_ID $HPARAMS_FILE | tail -1)