#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus-per-node=1
#SBATCH --array=1-18%18
#SBATCH --job-name=gru_basic
#SBATCH --time=2:30:0
#SBATCH --output=output/gru_basic_array_%A_%a.out

module purge
module load 2022
module load Miniconda3/4.12.0

HPARAMS_FILE=$HOME/MScThesis/code/jobs/hyper_basic_test.txt

cd $HOME/MScThesis/code
source activate thesis

cd $HOME/MScThesis/code
srun python gru.py $(head -$SLURM_ARRAY_TASK_ID $HPARAMS_FILE | tail -1)