#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --array=1-14%14
#SBATCH --job-name=gru_L2_test1
#SBATCH --time=1:0:0
#SBATCH --mem=32000M
#SBATCH --output=output/gru_L2_test1_%A_%a.out

module purge
module load 2022
module load Miniconda3/4.12.0

HPARAMS_FILE=$HOME/MScThesis/code/jobs/hyper_L2_test1.txt

cd $HOME/MScThesis/code
source activate thesis

cd $HOME/MScThesis/code
srun python gru.py $(head -$SLURM_ARRAY_TASK_ID $HPARAMS_FILE | tail -1)