#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --job-name=fcnn_test
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=01:00:00
#SBATCH --mem=32000M
#SBATCH --output=slurm_output_%A.out

module purge
module load 2022
module load Miniconda3/4.12.0

cd $HOME/MScThesis/code
source activate thesis

# Create data
srun python create_data.py -n_sims 5000
srun python create_data.py -n_sims 5000 -t_min -10 -t_max 10 -r_min -5 -r_max 5
# srun python fcnn.py
#  srun python fcnn.py -data_dir_train "data_t(0, 0)_r(0, 0)_none" -data_dir_test "data_t(-10, 10)_r(-5, 5)_none"