#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --job-name=data_creation
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=01:00:00
#SBATCH --mem=32000M
#SBATCH --output=slurm_output_%A.out

module purge
module load 2022
module load Miniconda3/4.12.0

# Your job starts in the directory where you call sbatch
cd $HOME/...
# Activate your environment
source activate thesis
# Run your code
srun python -u ...